#!/bin/bash

set -e

#export PACKER_LOG=1
rm devbox-15-04-iso_virtualbox.box || true
packer build -only virtualbox-iso packer.json
vagrant box remove devbox-15-04 || true
vagrant box add devbox-15-04 devbox-15-04-iso_virtualbox.box
