#!/bin/bash

set -e

#export PACKER_LOG=1
rm devbox-jessie-iso_virtualbox.box || true
packer build -only virtualbox-iso packer.json
vagrant box remove devbox-jessie || true
vagrant box add devbox-jessie devbox-jessie-iso_virtualbox.box
